name: Linter
on: push
jobs:
  lint-back:
    name: Lint backend code
    runs-on: ubuntu-latest
    env:
      working-directory: .
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm ci
      working-directory: ${{env.working-directory}}
    - name: Run ESLint
      run: npm run lint
      working-directory: ${{env.working-directory}}
  lint-front:
    name: Lint frontend code
    runs-on: ubuntu-latest
    env:
      working-directory: ui
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm ci
      working-directory: ${{env.working-directory}}
    - name: Run ESLint
      run: npm run lint
      working-directory: ${{env.working-directory}}